// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace TWLib.Streamer.Models
{
    public class DxfeedServiceSubReq : DxfeedRequest
    {

        public DxfeedServiceSubReq()
        {

        }

        public DxfeedServiceSubReq(string clientId, List<string>symbols)
        {
            ClientId = clientId;
            Data = new Data2();
            Data.Add = new Add2();
            Data.Add.Profile = symbols;
            Data.Add.Quote = symbols;
            Data.Add.Summary = symbols;
            Data.Add.Trade = symbols;
        }

        public class Add2
        {
            [JsonProperty("Trade")]
            public IList<string> Trade { get; set; }

            [JsonProperty("Quote")]
            public IList<string> Quote { get; set; }

            [JsonProperty("Summary")]
            public IList<string> Summary { get; set; }

            [JsonProperty("Profile")]
            public IList<string> Profile { get; set; }
        }

        public class Data2
        {
            [JsonProperty("add")]
            public Add2 Add { get; set; }
        }

        [JsonProperty("clientId")]
        public string ClientId { get; set; }

        [JsonProperty("channel")]
        [JsonConverter(typeof(StringEnumConverter))]
        public override DxfeedChannel Channel { get { return DxfeedChannel.SERVICESUB; } }

        [JsonProperty("data")]
        public Data2 Data { get; set; }

        public override string Serialize()
        {
            DxfeedServiceSubReq[] arr = new DxfeedServiceSubReq[] { this };
            return JsonConvert.SerializeObject(arr);
        }

        public override TWRequest Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<DxfeedServiceSubReq>(json);
        }
    }
}
