/*   This file is part of TWLib.
 *
 *    TWLib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TWLib is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TWLib.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************
 *
 *    Project available from here: https://github.com/martian73/TWLib.git
 ******************************************************************************
 */
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace TWLib.Streamer.Models
{

    public class DxfeedServiceSubAddEquityReq : DxfeedRequest
    {

        public DxfeedServiceSubAddEquityReq()
        {

        }

        public DxfeedServiceSubAddEquityReq(string clientId, List<string> symbols, int profiles =
            (int)ServiceDataType.PROFILE |
            (int)ServiceDataType.QUOTE |
            (int)ServiceDataType.SUMMARY |
            (int)ServiceDataType.TRADE)
        {

            ClientId = clientId;
            Data = new Data2();
            Data.Add = new Add2();

            if ((profiles & (int)ServiceDataType.PROFILE) > 0)
                Data.Add.Profile = symbols;

            if ((profiles & (int)ServiceDataType.QUOTE) > 0)
                Data.Add.Quote = symbols;

            if ((profiles & (int)ServiceDataType.SUMMARY) > 0)
                Data.Add.Summary = symbols;

            if ((profiles & (int)ServiceDataType.TRADE) > 0)
                Data.Add.Trade = symbols;
        }

        public class Add2
        {
            [JsonProperty("Trade")]
            public IList<string> Trade { get; set; }

            [JsonProperty("Quote")]
            public IList<string> Quote { get; set; }

            [JsonProperty("Summary")]
            public IList<string> Summary { get; set; }

            [JsonProperty("Profile")]
            public IList<string> Profile { get; set; }
        }

        public class Data2
        {
            [JsonProperty("add")]
            public Add2 Add { get; set; }
        }

        [JsonProperty("clientId")]
        public string ClientId { get; set; }

        [JsonProperty("channel")]
        [JsonConverter(typeof(StringEnumConverter))]
        public override DxfeedChannel Channel { get { return DxfeedChannel.SERVICESUB; } }

        [JsonProperty("data")]
        public Data2 Data { get; set; }

        public override string Serialize()
        {
            DxfeedServiceSubAddEquityReq[] arr = new DxfeedServiceSubAddEquityReq[] { this };
            return JsonConvert.SerializeObject(arr);
        }

        public override TWRequest Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<DxfeedServiceSubAddEquityReq>(json);
        }
    }
}

