// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;


namespace TWLib.Streamer.Models
{
    public class DxfeedMetaConnectReq : DxfeedRequest
    {
        public DxfeedMetaConnectReq()
        {

        }

        public DxfeedMetaConnectReq(string clientId, int timeout)
        {
            Advice = new Advice2();
            Advice.Timeout = timeout;
            ClientId = clientId;
        }

        public class Advice2
        {

            [JsonProperty("timeout")]
            public int Timeout { get; set; }
        }

        [JsonProperty("clientId")]
        public string ClientId { get; set; }

        [JsonProperty("channel")]
        [JsonConverter(typeof(StringEnumConverter))]
        public override DxfeedChannel Channel { get { return DxfeedChannel.METACONNECT; } }

        [JsonProperty("connectionType")]
        public string ConnectionType { get { return "websocket"; } }

        [JsonProperty("advice")]
        public Advice2 Advice { get; set; }

        public override string Serialize()
        {
            DxfeedMetaConnectReq[] arr = new DxfeedMetaConnectReq[] { this };
            return JsonConvert.SerializeObject(arr);
        }

        public override TWRequest Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<DxfeedMetaHandshakeReq>(json);
        }
    }
}
