/*   This file is part of TWLib.
 *
 *    TWLib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TWLib is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TWLib.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************
 *
 *    Project available from here: https://github.com/martian73/TWLib.git
 ******************************************************************************
 */
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;


namespace TWLib.Streamer.Models
{
    public class DxfeedMetaHandshakeRes : DxfeedResponse
    {
        public class Advice2
        {

            [JsonProperty("interval")]
            public int Interval { get; set; }

            [JsonProperty("timeout")]
            public int Timeout { get; set; }

            [JsonProperty("reconnect")]
            public string Reconnect { get; set; }
        }


        [JsonProperty("minimumVersion")]
        public string MinimumVersion { get; set; }

        [JsonProperty("clientId")]
        public string ClientId { get; set; }

        [JsonProperty("supportedConnectionTypes")]
        public IList<string> SupportedConnectionTypes { get; set; }

        [JsonProperty("advice")]
        public Advice2 Advice { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("successful")]
        public bool Successful { get; set; }

        public override string Serialize()
        {
            DxfeedMetaHandshakeRes[] arr = new DxfeedMetaHandshakeRes[] { this };
            return JsonConvert.SerializeObject(arr);
        }

        public override TWResponse Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<DxfeedMetaHandshakeRes>(json);
        }
    }
}

