// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace TWLib.Streamer.Models
{
    public class DxfeedMetaConnectRes : DxfeedResponse
    {
        public enum Reconnect
        {
            [EnumMember(Value = "retry")]
            RETRY
        }

        public class Advice2
        {

            [JsonProperty("interval")]
            public int Interval { get; set; }

            [JsonProperty("timeout")]
            public int Timeout { get; set; }

            [JsonProperty("reconnect")]
            [JsonConverter(typeof(StringEnumConverter))]
            public Reconnect Reconnect { get; set; }
        }

        [JsonProperty("advice")]
        public Advice2 Advice { get; set; }

        [JsonProperty("successful")]
        public bool Successful { get; set; }

    }
}
