/*   This file is part of TWLib.
 *
 *    TWLib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TWLib is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TWLib.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************
 *
 *    Project available from here: https://github.com/martian73/TWLib.git
 ******************************************************************************
 */
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;

namespace TWLib.Streamer.Models
{
    public class DxfeedMetaConnectRes : DxfeedResponse
    {
        public enum Reconnect
        {
            [EnumMember(Value = "retry")]
            RETRY
        }

        public class Advice2
        {

            [JsonProperty("interval")]
            public int Interval { get; set; }

            [JsonProperty("timeout")]
            public int Timeout { get; set; }

            [JsonProperty("reconnect")]
            [JsonConverter(typeof(StringEnumConverter))]
            public Reconnect Reconnect { get; set; }
        }

        [JsonProperty("advice")]
        public Advice2 Advice { get; set; }

        [JsonProperty("successful")]
        public bool Successful { get; set; }

    }
}

