// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace TWLib.Streamer.Models
{
    public class DxfeedMetaHandshakeReq : DxfeedRequest
    {
        public class Advice2
        {

            [JsonProperty("timeout")]
            public int Timeout { get; set; }

            [JsonProperty("interval")]
            public int Interval { get; set; }
        }

        public class Ext2
        {

            [JsonProperty("com.devexperts.auth.AuthToken")]
            public string ComDevexpertsAuthToken { get; set; }
        }

        [JsonProperty("advice")]
        public Advice2 Advice { get; set; }

        [JsonProperty("channel")]
        public override string Channel { get { return "/meta/handshake"; } }

        [JsonProperty("ext")]
        public Ext2 Ext { get; set; }

        [JsonProperty("minimumVersion")]
        public string MinimumVersion { get; set; }

        [JsonProperty("supportedConnectionTypes")]
        public IList<string> SupportedConnectionTypes { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        public override string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }

        public override TWRequest Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<DxfeedMetaHandshakeReq>(json);
        }

    }
}
