// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace TWLib.Streamer.Models
{
    public class StreamerTokens
    {
        public class Data2
        {

            [JsonProperty("token")]
            public string Token { get; set; }

            [JsonProperty("streamer-url")]
            public string StreamerUrl { get; set; }

            [JsonProperty("websocket-url")]
            public string WebsocketUrl { get; set; }

            [JsonProperty("level")]
            public string Level { get; set; }
        }

        [JsonProperty("data")]
        public Data2 Data { get; set; }

        [JsonProperty("context")]
        public string Context { get; set; }

    }
}
