// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;


namespace TWLib.Streamer.Models
{

    public class StwResponse : TWResponse
    {
        [JsonIgnore]
        public override StreamType StreamType
        {
            get
            {
                return StreamType.STWSTREAMER;
            }
        }

        [JsonProperty("request-id")]
        public int RequestId { get; set; }

        [JsonProperty("auth-token")]
        public string AuthToken { get; set; }

        [JsonProperty("action")]
        [JsonConverter(typeof(StringEnumConverter))]
        public StwAction Action { get; set; }

        [JsonProperty("value")]
        public IList<string> Value { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }


        public override TWResponse Deserialize(string json)
        {
            throw new NotImplementedException();
        }

        public override string Serialize()
        {
            throw new NotImplementedException();
        }
    }
}
