// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TWLib.Models
{
    public class Cometd
    {

        [JsonProperty("data")]
        public IList<object> Data { get; set; }

        [JsonProperty("channel")]
        public string Channel { get; set; }
    }
}
