/*   This file is part of TWLib.
 *
 *    TWLib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TWLib is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TWLib.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************
 *
 *    Project available from here: https://github.com/martian73/TWLib.git
 ******************************************************************************
 */
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;

namespace TWLib.Models
{
    public class MarginReport
    {
        public class Data2
        {
            [JsonProperty("account-number")]
            public string AccountNumber
            {
                get;
                set;
            }
            [JsonProperty("margin-calculation-type")]
            public string MarginCalculationType
            {
                get;
                set;
            }
            [JsonProperty("option-level")]
            public string OptionLevel
            {
                get;
                set;
            }
            [JsonProperty("margin-requirement")]
            public string MarginRequirement
            {
                get;
                set;
            }
            [JsonProperty("margin-requirement-effect")]
            public string MarginRequirementEffect
            {
                get;
                set;
            }
            [JsonProperty("maintenance-requirement")]
            public string MaintenanceRequirement
            {
                get;
                set;
            }
            [JsonProperty("maintenance-requirement-effect")]
            public string MaintenanceRequirementEffect
            {
                get;
                set;
            }
            [JsonProperty("buying-power")]
            public string BuyingPower
            {
                get;
                set;
            }
            [JsonProperty("buying-power-effect")]
            public string BuyingPowerEffect
            {
                get;
                set;
            }
            [JsonProperty("last-state-timestamp")]
            public long LastStateTimestamp
            {
                get;
                set;
            }
            [JsonProperty("underlyings")]
            public IList<object> Underlyings
            {
                get;
                set;
            }
        }
        [JsonProperty("data")]
        public Data2 Data
        {
            get;
            set;
        }
    }
}
