// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace TWLib.Models
{
    public class MarginReport
    {
        public class Data2
        {
            [JsonProperty("account-number")]
            public string AccountNumber { get; set; }

            [JsonProperty("margin-calculation-type")]
            public string MarginCalculationType { get; set; }

            [JsonProperty("option-level")]
            public string OptionLevel { get; set; }

            [JsonProperty("margin-requirement")]
            public string MarginRequirement { get; set; }

            [JsonProperty("margin-requirement-effect")]
            public string MarginRequirementEffect { get; set; }

            [JsonProperty("maintenance-requirement")]
            public string MaintenanceRequirement { get; set; }

            [JsonProperty("maintenance-requirement-effect")]
            public string MaintenanceRequirementEffect { get; set; }

            [JsonProperty("buying-power")]
            public string BuyingPower { get; set; }

            [JsonProperty("buying-power-effect")]
            public string BuyingPowerEffect { get; set; }

            [JsonProperty("last-state-timestamp")]
            public long LastStateTimestamp { get; set; }

            [JsonProperty("underlyings")]
            public IList<object> Underlyings { get; set; }
        }


        [JsonProperty("data")]
        public Data2 Data { get; set; }

    }
}
