// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;


namespace TWLib.Models
{
    public class MarketMetrics
    {
        public class OptionExpirationImpliedVolatility
        {

            [JsonProperty("expiration-date")]
            public string ExpirationDate { get; set; }

            [JsonProperty("option-chain-type")]
            public string OptionChainType { get; set; }

            [JsonProperty("settlement-type")]
            public string SettlementType { get; set; }

            [JsonProperty("implied-volatility")]
            public string ImpliedVolatility { get; set; }
        }

        public class LiquidityRunningState
        {

            [JsonProperty("sum")]
            public string Sum { get; set; }

            [JsonProperty("count")]
            public int Count { get; set; }

            [JsonProperty("started-at")]
            public string StartedAt { get; set; }
        }

        public class Item
        {

            [JsonProperty("symbol")]
            public string Symbol { get; set; }

            [JsonProperty("implied-volatility-index")]
            public string ImpliedVolatilityIndex { get; set; }

            [JsonProperty("implied-volatility-index-5-day-change")]
            public string ImpliedVolatilityIndex5DayChange { get; set; }

            [JsonProperty("implied-volatility-index-rank")]
            public string ImpliedVolatilityIndexRank { get; set; }

            [JsonProperty("tos-implied-volatility-index-rank")]
            public string TosImpliedVolatilityIndexRank { get; set; }

            [JsonProperty("tw-implied-volatility-index-rank")]
            public string TwImpliedVolatilityIndexRank { get; set; }

            [JsonProperty("tos-implied-volatility-index-rank-updated-at")]
            public string TosImpliedVolatilityIndexRankUpdatedAt { get; set; }

            [JsonProperty("implied-volatility-index-rank-source")]
            public string ImpliedVolatilityIndexRankSource { get; set; }

            [JsonProperty("implied-volatility-percentile")]
            public string ImpliedVolatilityPercentile { get; set; }

            [JsonProperty("implied-volatility-updated-at")]
            public string ImpliedVolatilityUpdatedAt { get; set; }

            [JsonProperty("liquidity-value")]
            public string LiquidityValue { get; set; }

            [JsonProperty("liquidity-rank")]
            public string LiquidityRank { get; set; }

            [JsonProperty("liquidity-rating")]
            public int LiquidityRating { get; set; }

            [JsonProperty("updated-at")]
            public string UpdatedAt { get; set; }

            [JsonProperty("option-expiration-implied-volatilities")]
            public IList<OptionExpirationImpliedVolatility> OptionExpirationImpliedVolatilities { get; set; }

            [JsonProperty("liquidity-running-state")]
            public LiquidityRunningState LiquidityRunningState { get; set; }

            [JsonProperty("beta")]
            public string Beta { get; set; }

            [JsonProperty("corr-spy-3month")]
            public string CorrSpy3month { get; set; }

            [JsonProperty("dividend-rate-per-share")]
            public string DividendRatePerShare { get; set; }

            [JsonProperty("annual-dividend-per-share")]
            public string AnnualDividendPerShare { get; set; }

            [JsonProperty("dividend-ex-date")]
            public string DividendExDate { get; set; }

            [JsonProperty("listed-market")]
            public string ListedMarket { get; set; }

            [JsonProperty("lendability")]
            public string Lendability { get; set; }
        }

        public class Data2
        {

            [JsonProperty("items")]
            public IList<Item> Items { get; set; }
        }


        [JsonProperty("data")]
        public Data2 Data { get; set; }

    }
}
