/*   This file is part of TWLib.
 *
 *    TWLib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TWLib is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TWLib.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************
 *
 *    Project available from here: https://github.com/martian73/TWLib.git
 ******************************************************************************
 */
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator
using Newtonsoft.Json;
using System.Collections.Generic;
namespace TWLib.Models
{
    public class Orders
    {
        public class BuyingPowerEffect
        {
            [JsonProperty("change-in-margin-requirement")]
            public string ChangeInMarginRequirement
            {
                get;
                set;
            }
            [JsonProperty("change-in-margin-requirement-effect")]
            public string ChangeInMarginRequirementEffect
            {
                get;
                set;
            }
            [JsonProperty("change-in-buying-power")]
            public string ChangeInBuyingPower
            {
                get;
                set;
            }
            [JsonProperty("change-in-buying-power-effect")]
            public string ChangeInBuyingPowerEffect
            {
                get;
                set;
            }
            [JsonProperty("current-buying-power")]
            public string CurrentBuyingPower
            {
                get;
                set;
            }
            [JsonProperty("current-buying-power-effect")]
            public string CurrentBuyingPowerEffect
            {
                get;
                set;
            }
            [JsonProperty("new-buying-power")]
            public string NewBuyingPower
            {
                get;
                set;
            }
            [JsonProperty("new-buying-power-effect")]
            public string NewBuyingPowerEffect
            {
                get;
                set;
            }
            [JsonProperty("isolated-order-margin-requirement")]
            public string IsolatedOrderMarginRequirement
            {
                get;
                set;
            }
            [JsonProperty("isolated-order-margin-requirement-effect")]
            public string IsolatedOrderMarginRequirementEffect
            {
                get;
                set;
            }
            [JsonProperty("is-spread")]
            public bool IsSpread
            {
                get;
                set;
            }
            [JsonProperty("impact")]
            public string Impact
            {
                get;
                set;
            }
            [JsonProperty("effect")]
            public string Effect
            {
                get;
                set;
            }
        }
        public class FeeCalculation
        {
            [JsonProperty("regulatory-fees")]
            public string RegulatoryFees
            {
                get;
                set;
            }
            [JsonProperty("regulatory-fees-effect")]
            public string RegulatoryFeesEffect
            {
                get;
                set;
            }
            [JsonProperty("clearing-fees")]
            public string ClearingFees
            {
                get;
                set;
            }
            [JsonProperty("clearing-fees-effect")]
            public string ClearingFeesEffect
            {
                get;
                set;
            }
            [JsonProperty("commission")]
            public string Commission
            {
                get;
                set;
            }
            [JsonProperty("commission-effect")]
            public string CommissionEffect
            {
                get;
                set;
            }
            [JsonProperty("proprietary-index-option-fees")]
            public string ProprietaryIndexOptionFees
            {
                get;
                set;
            }
            [JsonProperty("proprietary-index-option-fees-effect")]
            public string ProprietaryIndexOptionFeesEffect
            {
                get;
                set;
            }
            [JsonProperty("total-fees")]
            public string TotalFees
            {
                get;
                set;
            }
            [JsonProperty("total-fees-effect")]
            public string TotalFeesEffect
            {
                get;
                set;
            }
        }

        public class Data2
        {
            [JsonProperty("buying-power-effect")]
            public BuyingPowerEffect BuyingPowerEffect
            {
                get;
                set;
            }

            [JsonProperty("fee-calculation")]
            public FeeCalculation FeeCalculation
            {
                get;
                set;
            }
        }
        public class Error3
        {
            [JsonProperty("code")]
            public string Code
            {
                get;
                set;
            }
            [JsonProperty("message")]
            public string Message
            {
                get;
                set;
            }
        }
        public class Error2
        {
            [JsonProperty("code")]
            public string Code
            {
                get;
                set;
            }
            [JsonProperty("message")]
            public string Message
            {
                get;
                set;
            }
            [JsonProperty("errors")]
            public IList<Error3> Errors
            {
                get;
                set;
            }
        }
        [JsonProperty("data")]
        public Data2 Data
        {
            get;
            set;
        }
        [JsonProperty("api-version")]
        public string ApiVersion
        {
            get;
            set;
        }
        [JsonProperty("error")]
        public Error2 Error
        {
            get;
            set;
        }
    }
}
