// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TWLib.Models
{
    public class Order
    {
        public class Leg
        {
            [JsonProperty("instrument-type")]
            public string InstrumentType { get; set; }

            [JsonProperty("symbol")]
            public string Symbol { get; set; }

            [JsonProperty("quantity")]
            public double Quantity { get; set; }

            [JsonProperty("action")]
            public string Action { get; set; }
        }

        [JsonProperty("order-type")]
        public string OrderType { get; set; }

        [JsonProperty("time-in-force")]
        public string TimeInForce { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("price-effect")]
        public string PriceEffect { get; set; }

        [JsonProperty("legs")]
        public IList<Leg> Legs { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

    }
}
