/*   This file is part of TWLib.
 *
 *    TWLib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TWLib is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TWLib.  If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************
 *
 *    Project available from here: https://github.com/martian73/TWLib.git
 ******************************************************************************
 */
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using System.Collections.Generic;

namespace TWLib.Models
{
    public class Positions
    {
        public class Item
        {
            [JsonProperty("account-number")]
            public string AccountNumber
            {
                get;
                set;
            }
            [JsonProperty("symbol")]
            public string Symbol
            {
                get;
                set;
            }
            [JsonProperty("instrument-type")]
            public InstrumentType InstrumentType
            {
                get;
                set;
            }
            [JsonProperty("underlying-symbol")]
            public string UnderlyingSymbol
            {
                get;
                set;
            }
            [JsonProperty("quantity")]
            public int Quantity
            {
                get;
                set;
            }
            [JsonProperty("quantity-direction")]
            public QuantityDirection QuantityDirection
            {
                get;
                set;
            }
            [JsonProperty("close-price")]
            public string ClosePrice
            {
                get;
                set;
            }
            [JsonProperty("average-open-price")]
            public string AverageOpenPrice
            {
                get;
                set;
            }
            [JsonProperty("average-yearly-market-close-price")]
            public string AverageYearlyMarketClosePrice
            {
                get;
                set;
            }
            [JsonProperty("average-daily-market-close-price")]
            public string AverageDailyMarketClosePrice
            {
                get;
                set;
            }
            [JsonProperty("mark")]
            public string Mark
            {
                get;
                set;
            }
            [JsonProperty("mark-price")]
            public string MarkPrice
            {
                get;
                set;
            }
            [JsonProperty("multiplier")]
            public int Multiplier
            {
                get;
                set;
            }
            [JsonProperty("cost-effect")]
            public string CostEffect
            {
                get;
                set;
            }
            [JsonProperty("is-suppressed")]
            public bool IsSuppressed
            {
                get;
                set;
            }
            [JsonProperty("is-frozen")]
            public bool IsFrozen
            {
                get;
                set;
            }
            [JsonProperty("restricted-quantity")]
            public int RestrictedQuantity
            {
                get;
                set;
            }
            [JsonProperty("expires-at")]
            public string ExpiresAt
            {
                get;
                set;
            }
            [JsonProperty("realized-day-gain")]
            public string RealizedDayGain
            {
                get;
                set;
            }
            [JsonProperty("realized-day-gain-effect")]
            public string RealizedDayGainEffect
            {
                get;
                set;
            }
            [JsonProperty("realized-day-gain-date")]
            public string RealizedDayGainDate
            {
                get;
                set;
            }
            [JsonProperty("realized-today")]
            public string RealizedToday
            {
                get;
                set;
            }
            [JsonProperty("realized-today-effect")]
            public string RealizedTodayEffect
            {
                get;
                set;
            }
            [JsonProperty("realized-today-date")]
            public string RealizedTodayDate
            {
                get;
                set;
            }
            [JsonProperty("created-at")]
            public string CreatedAt
            {
                get;
                set;
            }
            [JsonProperty("updated-at")]
            public string UpdatedAt
            {
                get;
                set;
            }
        }
        public class Data2
        {
            [JsonProperty("items")]
            public IList<Item> Items
            {
                get;
                set;
            }
        }
        [JsonProperty("data")]
        public Data2 Data
        {
            get;
            set;
        }
        [JsonProperty("api-version")]
        public string ApiVersion
        {
            get;
            set;
        }
        [JsonProperty("context")]
        public string Context
        {
            get;
            set;
        }
    }
}
