// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TWLib.Models
{
    public class PublicWatchlists
    {
        public class WatchlistEntry
    {

        [JsonProperty("symbol")]
        public string Symbol { get; set; }

        [JsonProperty("instrument_type")]
        public string InstrumentType { get; set; }
    }

    public class Item
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("watchlist-entries")]
        public IList<WatchlistEntry> WatchlistEntries { get; set; }

        [JsonProperty("group-name")]
        public string GroupName { get; set; }
    }

    public class Data2
    {

        [JsonProperty("items")]
        public IList<Item> Items { get; set; }
    }


    [JsonProperty("data")]
    public Data2 Data { get; set; }

    [JsonProperty("api-version")]
    public string ApiVersion { get; set; }

    [JsonProperty("context")]
    public string Context { get; set; }

}
    }
