// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TWLib.Models
{
    public class SymbolSearch
    {
        public class Item
        {

            [JsonProperty("symbol")]
            public string Symbol { get; set; }

            [JsonProperty("description")]
            public string Description { get; set; }
        }

        public class Data2
        {

            [JsonProperty("items")]
            public IList<Item> Items { get; set; }
        }


        [JsonProperty("data")]
        public Data2 Data { get; set; }

    }
}
