// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TWLib.Models;

namespace TWLib.Models
{

    public class Data
    {
        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("external-id")]
        public string ExternalId { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }
    }

    public class ValidateResponse
    {


        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("api-version")]
        public string ApiVersion { get; set; }

        [JsonProperty("context")]
        public string Context { get; set; }
    }
}
